# Generated by Django 2.1.5 on 2020-10-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='artist',
            new_name='author',
        ),
    ]
