# Generated by Django 2.1.5 on 2020-10-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0002_auto_20201007_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
