# Generated by Django 2.1.5 on 2020-10-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0003_auto_20201007_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='artist',
            new_name='borrower',
        ),
    ]
